/**
 *
 * $Id$
 */
package empresa.validation;

import empresa.Attribute;
import empresa.Entity;

/**
 * A sample validator interface for {@link empresa.Column}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ColumnValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateTitle(String value);
	boolean validateFilter(boolean value);
	boolean validateEditable(boolean value);
	boolean validateSource(Entity value);
	boolean validateAttribute(Attribute value);
}
