/**
 *
 * $Id$
 */
package empresa.validation;

import empresa.DBSystem;
import empresa.Entity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link empresa.DBServer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DBServerValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSystemManager(DBSystem value);
	boolean validateToken(String value);
	boolean validatePassword(String value);
	boolean validateRelatedCollections(EList<Entity> value);
}
