/**
 *
 * $Id$
 */
package empresa.validation;


/**
 * A sample validator interface for {@link empresa.Graphic2D}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Graphic2DValidator {
	boolean validate();

	boolean validateLabelStringXAxes(String value);
	boolean validateDisplayGridLinesXAxes(boolean value);
	boolean validateColorGridLinesXAxes(String value);
	boolean validateLabelStringYAxes(String value);
	boolean validateDisplayGridLinesYAxes(boolean value);
	boolean validateColorGridLinesYAxes(String value);
}
