/**
 *
 * $Id$
 */
package empresa.validation;

import empresa.Action;
import empresa.Column;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link empresa.Table}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableValidator {
	boolean validate();

	boolean validateRegistersPerPage(int value);
	boolean validateActions(Action value);
	boolean validateColumns(EList<Column> value);
	boolean validateSearch(boolean value);
	boolean validateAdd(boolean value);
}
